#!/usr/bin/env bash
#Script install and start Nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
