#!/usr/bin/env bash
# Script handles various signals

terminate() {
  rm /var/run/holbertonscript.pid
  exit
}

echo "$$" > /var/run/holbertonscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminate' SIGTERM
  trap 'terminate' SIGQUIT
done
