#!/usr/bin/env bash
#print "Holberton School" with "bad luck" @4 & "good luck" @8
i=1
while [ $i -lt 11 ]
do
    if [ $i -eq 4 ]
    then
	echo "bad luck"
    elif [ $i -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    (( i++ ))
done
