#!/usr/bin/env bash
#print "Best School" x8, "bad luck" on 4th & "good luck" on 8th iteratiom

i=0
while [ "$i" -lt 10 ]
do
    if [ "$i" -eq 3 ]
    then
	echo "bad luck"
    elif [ "$i" -eq 7 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( i++ ))
done
