#!/usr/bin/env bash
#print numbers 1-20, if 4 "bad luck from China",
#9 "bad luck from Japan", 17 "bad luck from Italy"

i=1
while [ "$i" -le 20 ]
do
    case "$i" in
	4)
	    echo "$i"
	    echo "bad luck from China"
	    ;;
	9)
	    echo "$i"
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "$i"
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo "$i"
	    ;;
    esac
    (( i++ ))
done
