#!/usr/bin/env bash
#nested while loop to display hours and minutes
hour=0
minutes=1
while [ $hour -le 12 ]
do
    minutes=1
    echo "Hour: $hour"
    while [ $minutes -le 59 ]
    do
	echo $minutes
	(( minutes++ ))
    done
    (( hour++ ))
done
