#!/usr/bin/env bash
#This script displays hours and their minutes

h=0
m=1

while [ "$h" -lt 13 ]
do
    echo "Hour: $h"
    (( m = 1 ))
    while [ "$m" -lt 60 ]
    do
	echo "$m"
	(( m += 1 ))
    done
    (( h += 1 ))
done
